export const PARCOURS = [
  { id: "donnees",      label: "Des données sensibles",             color: "#f59e0b", cards: [18,25,28,29,35,38] },
  { id: "roles",        label: "Des rôles pour l'IA",               color: "#10b981", cards: [1,2,3,4,5,6,7,25,29,31] },
  { id: "transparence", label: "Un peu de transparence",            color: "#ef4444", cards: [11,17,27,34] },
  { id: "scribe",       label: "L'IA scribe",                       color: "#8b5cf6", cards: [16,17,20] },
  { id: "competences",  label: "Des compétences à ne pas oublier",  color: "#06b6d4", cards: [6,8,14,15,16,20,26,36] },
  { id: "societe",      label: "Impact sur la société",             color: "#ec4899", cards: [10,24,32,33,30] },
  { id: "planete",      label: "Impact sur la planète",             color: "#22c55e", cards: [8,13,12,19,35] },
  { id: "encadrer",     label: "Soutenir et encadrer",              color: "#f97316", cards: [1,2,4,6,26,28,31] },
  { id: "veracite",     label: "Ce résultat est-il juste et vrai ?",color: "#3b82f6", cards: [5,9,14,22,37,39] },
  { id: "prompt",       label: "Prompter promptement",              color: "#d946ef", cards: [21,23] },
]

export const questions = [
  { id: 1,  titre: "IA mentor",              situation: "J'ai entendu parler d'une IA mentor : elle me sert de coach, en me donnant des commentaires au fur et à mesure de mon travail.", altA: "Oui, c'est plus facile et plus accessible qu'un prof qui a rarement le temps de me guider.", altB: "Non, même si j'ai besoin d'un coach, je préfère tracer mon chemin par mes propres moyens." },
  { id: 2,  titre: "IA tuteur",              situation: "J'ai entendu parler d'une IA tuteur : elle prendrait en charge mon apprentissage, à la place du prof.", altA: "Pourquoi pas, le prof n'est pas toujours disponible pour m'aider.", altB: "Surtout pas, ça reste une machine, elle ne me connaît pas et elle demande trop de données personnelles." },
  { id: 3,  titre: "IA équipière",           situation: "J'ai entendu parler d'une IA équipière : dans un travail de groupe, elle fait équipe avec nous en donnant son avis.", altA: "Oui, ce serait pas mal d'avoir un autre avis, même si c'est celui d'une machine.", altB: "Non, c'est déjà difficile de s'entendre entre nous, alors avec une voix en plus…" },
  { id: 4,  titre: "IA coach",               situation: "J'ai entendu parler d'une IA coach : elle me pose des questions sur ce que j'ai fait, sur ce que je pense avoir réussi et elle me donne des conseils pour progresser.", altA: "Oui, j'ai toujours rêvé d'avoir une voix qui m'aiderait à savoir où j'en suis !", altB: "Non, ça va pas du tout ! Elle va collecter plein de données sur mon travail. C'est trop personnel pour lui laisser tout ça !" },
  { id: 5,  titre: "IA simulateur",          situation: "J'utilise une IA-simulateur. Elle reproduit une situation, comme si c'était réel. Ça fait jeu vidéo, et c'est motivant.", altA: "Oui, c'est quand même mieux qu'une étude de cas avec plein de questions.", altB: "Non, une simulation reste une simulation : elle ne représente pas assez bien ce qu'on voit dans la vraie vie." },
  { id: 6,  titre: "IA outil",               situation: "J'utilise une IA-outil. Elle est spécialisée dans une tâche précise (programmation, travail sur des textes, génération d'images…).", altA: "Oui, elle sera plus efficace sur ce qu'on cherche à faire.", altB: "Non, on a besoin de travailler ces compétences. Avec l'IA, on ne pourra jamais les entraîner correctement." },
  { id: 7,  titre: "IA soutien",             situation: "Cette IA est là pour aider les élèves qui ont des difficultés bien identifiées. Elle leur sert de béquille pour faire ce qu'ils ne seraient pas capables de faire.", altA: "Oui, sans IA, il est bien difficile de leur apporter de l'aide.", altB: "Non, ce n'est pas juste pour les autres qui ne bénéficieront pas de cette IA." },
  { id: 8,  titre: "Recherche documentaire", situation: "Pour une recherche documentaire générale, j'utilise une IA générative, c'est bien plus rapide !", altA: "Une IA générative : on passe plus rapidement au travail de compréhension, de liens, de traitement des données.", altB: "Un moteur de recherche : ça demande de critiquer les résultats et de sélectionner les informations utiles, avec leurs sources." },
  { id: 9,  titre: "Un résultat préoccupant",situation: "J'ai utilisé l'IA, mais je trouve que le résultat n'est pas à la hauteur de ce que j'espérais.", altA: "Je retente, jusqu'à ce que le résultat soit satisfaisant.", altB: "Je retente mais pas trop, il paraît que ça consomme beaucoup d'énergie et de ressources." },
  { id: 10, titre: "Justice ?",              situation: "J'ai fait seul mon devoir à la maison et je l'ai rendu, mais j'ai une moins bonne note que d'autres qui ont utilisé l'IA.", altA: "Je réagis. Il faut que les profs soient capables de gérer cette injustice.", altB: "Je ne fais rien. Ça se reproduira, et ça ne va pas m'encourager à continuer comme ça." },
  { id: 11, titre: "Confiance ?",            situation: "J'ai terminé d'écrire un texte. Le prof se montre méfiant. Il pense que j'ai utilisé une IA car c'est meilleur que d'habitude.", altA: "Je continuerai à faire comme ça. Je n'ai rien à me reprocher.", altB: "J'utilise un site qui permet de vérifier si mon texte est ressemblant à ce qu'une IA pourrait produire." },
  { id: 12, titre: "Gaspillage",             situation: "J'ai testé l'outil ComparIA. J'ai vu toutes les ressources que j'ai utilisées pour mes demandes à l'IA. C'est énorme…", altA: "Tant pis, si je me préoccupe de cela, je ne ferai plus grand-chose.", altB: "Quand même, ça me gêne. Je vais essayer de trouver des pratiques un peu plus responsables." },
  { id: 13, titre: "Grand ou petit modèle ?",situation: "Je privilégie les grands modèles d'IA (Gemini, ChatGPT, Mistral, Claude…), plutôt que les modèles hébergés en local dans mon établissement.", altA: "Oui, j'ai l'habitude avec ces outils. C'est plus simple.", altB: "Non, il paraît que les modèles en local sont plus petits, moins consommateurs, mais ils sont moins accessibles." },
  { id: 14, titre: "Où se trouve la source ?",situation: "J'ai fait une recherche avec l'IA, mais on m'a demandé les sources. Et l'IA que j'utilise ne me la donne pas.", altA: "Tant pis, on fera sans, ce n'est pas si important.", altB: "Quand même, je vais utiliser un moteur de recherche ou des livres, ça existe encore." },
  { id: 15, titre: "Les deux à la fois ?",   situation: "J'ai utilisé un moteur de recherche, et j'ai vu qu'il proposait d'utiliser une IA pour avoir un résumé des résultats.", altA: "C'est parfait, je ne suis plus obligé de cliquer sur les liens et de lire les résultats !", altB: "C'est limité, je ne peux même plus faire mon choix d'informations moi-même !" },
  { id: 16, titre: "Aide à l'écriture",      situation: "Je dois écrire un texte. Quel travail vais-je demander à l'IA ?", altA: "Quitte à faire, tout le travail à ma place.", altB: "De la reformulation du texte que j'ai écrit moi-même." },
  { id: 17, titre: "Transparence",           situation: "Je dois rendre un texte. Je l'ai fait en partie avec de l'IA.", altA: "Je rends mon travail, sans aucune précision.", altB: "Je copie et colle ma demande à l'IA, le prof saura comment je l'ai utilisée." },
  { id: 18, titre: "Nourrir une IA",         situation: "Je voudrais que l'IA retravaille le fichier que j'ai créé (un exposé, un texte, peu importe).", altA: "Aucun problème, même si l'IA va conserver mon fichier et le réutiliser plus tard.", altB: "Pas question de la laisser utiliser ce que j'ai fait. C'est moi le propriétaire." },
  { id: 19, titre: "Calculatrice de luxe",   situation: "Pour faire un calcul, je demande directement à l'IA. C'est moins galère que de sortir la calculatrice.", altA: "Oui, ça permet d'aller plus vite.", altB: "Non, inutile d'utiliser un outil aussi puissant et consommateur pour un truc aussi facile." },
  { id: 20, titre: "Qui fera le résumé ?",   situation: "Je dois faire un exposé pour résumer tout un sujet.", altA: "Je demande à l'IA de faire la synthèse de ce que j'ai trouvé. Rapide et efficace.", altB: "Je fais la synthèse moi-même, sinon, je ne comprendrai rien au sujet." },
  { id: 21, titre: "Ultra rapide",           situation: "Je dois me dépêcher. J'ai une demande à faire à l'IA.", altA: "Je fais la demande comme sur un moteur de recherche, quitte à l'améliorer par la suite.", altB: "Je prends le temps de bien faire ma première demande. Ça m'évitera d'en faire d'autres pour préciser la réponse." },
  { id: 22, titre: "Doutes",                 situation: "J'ai fait une recherche avec l'IA et j'ai des doutes sur les résultats.", altA: "Je compare avec les résultats d'autres IA.", altB: "Je reste sur ces résultats. D'autres IA ne m'apporteront rien de plus." },
  { id: 23, titre: "En une fois ou en plein de fois", situation: "Je fais une demande à l'IA. Quelle sera la stratégie que je vais adopter ?", altA: "Je le fais en plusieurs fois, en précisant mes demandes.", altB: "Je travaille ma demande pour avoir un résultat acceptable rapidement." },
  { id: 24, titre: "Théorie du remplacement",situation: "J'ai entendu parler de la théorie du remplacement. Il paraît que de nombreux emplois seront détruits car remplacés par l'IA.", altA: "Même pas peur. On trouvera d'autres emplois dans le futur, on s'adaptera.", altB: "Ça me stresse. Je ne vais pas commencer à me former à un métier qui pourrait disparaître." },
  { id: 25, titre: "Un peu d'entraînement", situation: "Je demande à l'IA de créer des exercices pour que je puisse réviser. Mais pour être efficace…", altA: "Je lui donne uniquement les cours de mes profs.", altB: "Je lui demande de chercher où elle veut, sans la restreindre." },
  { id: 26, titre: "Intuition de départ",    situation: "J'ai un exposé à faire. Je ne sais pas comment commencer.", altA: "Je demande à l'IA de me donner le départ. Je continuerai moi-même ensuite.", altB: "Je veux commencer moi-même, sinon, je ne maîtrise pas le sujet. L'IA pourra m'aider plus tard, pour d'autres tâches." },
  { id: 27, titre: "Absence de cadre",       situation: "Dans mon établissement scolaire, il n'y a pas de règle sur l'utilisation de l'IA. Du coup, on ne sait pas si on peut l'utiliser ou pas.", altA: "Je préfère éviter au maximum de l'utiliser, ça pourrait toujours m'être reproché.", altB: "Je l'utilise quand même, s'il n'y a pas de cadre, c'est qu'il n'y a pas de problème." },
  { id: 28, titre: "Coaching par l'IA",      situation: "J'ai des difficultés et on me propose de tester une IA qui va me coacher.", altA: "Oui, ça peut toujours m'aider.", altB: "Non, il lui faudra plein de données sur moi, et je n'ai pas envie de ça." },
  { id: 29, titre: "L'IA va m'orienter",     situation: "Une IA conseillère d'orientation est en expérimentation. Elle serait capable de m'orienter, et de participer aux procédures d'admission.", altA: "Oui, ça ne sera pas pire que les jurys qui ne sont pas toujours justes.", altB: "Non, c'est mon avenir et mes données, je ne veux pas qu'une IA puisse influencer mon destin." },
  { id: 30, titre: "Une IA magique",         situation: "Une IA agentique est capable de me donner des réponses en faisant plusieurs tâches l'une après l'autre. C'est pratique : je donne ce qu'il y a à faire, et je récupère le résultat !", altA: "Oui, c'est tellement plus rapide que de décomposer toutes ces tâches !", altB: "Non, je n'ai aucun moyen de vérifier et de valider ce qu'elle fait, et de corriger s'il y a besoin." },
  { id: 31, titre: "Chatbot motivationnel",  situation: "On m'a proposé de tester un chatbot motivationnel. Je parle avec lui quand je suis démotivé, et il m'encourage.", altA: "Oui, ça aide quand on ne trouve personne pour se rebooster.", altB: "Non, ça reste une machine programmée, pas un ami ou un psy." },
  { id: 32, titre: "IA sélective 1",         situation: "Dans ma classe, on nous propose des comptes pour utiliser une IA pro, mais il n'y a pas assez de comptes pour tout le monde.", altA: "On les réserve pour les personnes les plus bosseuses, pour qu'elles continuent à performer.", altB: "On les réserve aux personnes en difficulté, pour les aider à s'améliorer." },
  { id: 33, titre: "IA sélective 2",         situation: "Dans ma classe, on nous propose des comptes pour utiliser une IA pro, mais il n'y a pas assez de comptes pour tout le monde.", altA: "On les réserve pour une partie de la classe, tant pis pour l'égalité.", altB: "Soit c'est l'IA pour tout le monde, soit c'est l'IA pour personne." },
  { id: 34, titre: "Trop de triche !",       situation: "Dans ma classe, il y a trop d'élèves qui utilisent l'IA pour les évals. Les profs s'en rendent compte et cherchent des solutions.", altA: "Ils devraient tout interdire et renforcer les moyens pour le contrôler.", altB: "Ils devraient nous encourager à dire quand et comment on utilise l'IA, notamment pour les DM." },
  { id: 35, titre: "Illustrations",          situation: "J'ai besoin d'images pour illustrer un exposé.", altA: "Je demande à une IA générative pour les créer rapidement, selon mes instructions.", altB: "Je demande à un moteur de recherche, surtout que je ne sais pas exactement ce que je voudrais." },
  { id: 36, titre: "Exposé",                 situation: "Je dois faire un exposé. Je ne peux pas le faire seul, il me faut de l'aide.", altA: "Je préfère l'IA, c'est plus rapide et pratique.", altB: "Je préfère le groupe de travail, c'est plus convivial." },
  { id: 37, titre: "Supériorité",            situation: "Je fais une demande à une IA américaine, pour savoir quels sont les meilleurs scientifiques de l'histoire. Elle me sort 10 noms de savants blancs, parlant anglais, tous des hommes.", altA: "C'est comme ça, c'est possible que ce soit ces personnes qui ont marqué l'histoire des sciences.", altB: "Il doit y avoir un biais, puisque c'est une IA américaine." },
  { id: 38, titre: "Mettre les mains dans le cambouis", situation: "On me propose un cours sur le fonctionnement des IA : les algorithmes, les modèles d'entraînement, etc.", altA: "Inutile. Je ne veux pas devenir informaticien !", altB: "Utile, j'ai besoin de savoir comment ces outils marchent pour mieux comprendre leurs résultats." },
  { id: 39, titre: "Bleu, blanc, rouge ?",   situation: "J'ai le choix entre deux modèles d'IA, qui ont une seule différence : leur nationalité.", altA: "Je préfère le modèle français, même s'il était un peu plus cher.", altB: "Je préfère le modèle américain ou chinois, peut-être plus performant et plus utilisé dans le monde." },
]

export const ICON_KEYS = {
  1: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  2: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  3: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  4: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  5: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  6: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  7: { a: ["img_inclusivity.png"], b: ["img_equality.png"] },
  8: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  9: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  10: { a: ["img_equality.png"], b: ["img_bonpublic.png"] },
  11: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  12: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  13: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  14: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  15: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  16: { a: ["img_USERascendant.png", "img_delestage.png"], b: ["img_Integrite.png", "img_MonteeCptces.png"] },
  17: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  18: { a: ["img_data.png"], b: ["img_datacloud.png"] },
  19: { a: ["img_Gaspillage.png", "img_delestage.png"], b: ["img_Frugalite.png", "img_MonteeCptces.png"] },
  20: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  21: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  22: { a: ["img_critique.png", "img_Gaspillage.png"], b: ["img_delestage.png", "img_Frugalite.png"] },
  23: { a: ["img_delestage.png", "img_Gaspillage.png"], b: ["img_MonteeCptces.png", "img_Frugalite.png"] },
  24: { a: ["img_USERascendant.png"], b: ["img_IAascendant.png"] },
  25: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  26: { a: ["img_delestage.png", "img_IAascendant.png"], b: ["img_MonteeCptces.png", "img_USERascendant.png"] },
  27: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  28: { a: ["img_bonpublic.png", "img_data.png"], b: ["img_critique.png", "img_datacloud.png"] },
  29: { a: ["img_IAascendant.png", "img_data.png"], b: ["img_Integrite.png", "img_datacloud.png"] },
  30: { a: ["img_BoiteNoire.png", "img_IAascendant.png"], b: ["img_Tsprence.png", "img_USERascendant.png"] },
  31: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  32: { a: ["img_Inegalite.png"], b: ["img_equality.png"] },
  33: { a: ["img_USERascendant.png", "img_Errors.png"], b: ["img_equality.png", "img_Integrite.png"] },
  34: { a: ["img_Integrite.png", "img_equality.png"], b: ["img_Integrite.png", "img_inclusivity.png"] },
  35: { a: ["img_Robbery.png"], b: ["img_critique.png"] },
  36: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  37: { a: ["img_bonpublic.png", "img_Inegalite.png"], b: ["img_critique.png", "img_inclusivity.png"] },
  38: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
  39: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
};
export const ICON_MAX = {
  "img_USERascendant.png": 13,
  "img_Frugalite.png": 10,
  "img_Gaspillage.png": 10,
  "img_Integrite.png": 9,
  "img_IAascendant.png": 8,
  "img_delestage.png": 8,
  "img_critique.png": 8,
  "img_MonteeCptces.png": 7,
  "img_bonpublic.png": 7,
  "img_equality.png": 5,
  "img_data.png": 4,
  "img_datacloud.png": 4,
  "img_inclusivity.png": 3,
  "img_Duplicite.png": 3,
  "img_Inegalite.png": 2,
  "img_inclusion.png": 2,
  "img_BoiteNoire.png": 1,
  "img_Tsprence.png": 1,
  "img_Errors.png": 1,
  "img_Robbery.png": 1
};
export const BILAN_CARDS = [
  {
    img1: "img_bonpublic.png",
    title1: "Bon public",
    desc1: "Tu acceptes d'utiliser ces outils, sans trop te pr\u00e9occuper de leur fonctionnement ou de leurs limites. Tant qu'ils fonctionnent, le reste t'importe peu.",
    img2: "img_critique.png",
    title2: "Esprit critique",
    desc2: "Pas question d'utiliser des outils sans comprendre leurs enjeux. Il faut que tu comprennes tous les aspects, toutes les cons\u00e9quences de leur utilisation.",
  },
  {
    img1: "img_delestage.png",
    title1: "D\u00e9lestage cognitif",
    desc1: "Tu abandonnes \u00e0 l'IA des t\u00e2ches qui sont importantes pour le d\u00e9veloppement g\u00e9n\u00e9ral de tes comp\u00e9tences.",
    img2: "img_MonteeCptces.png",
    title2: "Mont\u00e9e en comp\u00e9tences",
    desc2: "Tu gardes la main sur le d\u00e9veloppement de tes comp\u00e9tences, en utilisant l'IA pour des t\u00e2ches pr\u00e9cises, mais pas essentielles.",
  },
  {
    img1: "img_Duplicite.png",
    title1: "Duplicit\u00e9",
    desc1: "Tu utilises l'IA de fa\u00e7on cach\u00e9e, sans la d\u00e9clarer et parfois, en faisant passer son travail pour le tien.",
    img2: "img_Integrite.png",
    title2: "Int\u00e9grit\u00e9",
    desc2: "Tu es transparent sur ton utilisation de l'IA. Tu la d\u00e9clares de fa\u00e7on honn\u00eate, en pr\u00e9cisant o\u00f9 et pourquoi tu l'as utilis\u00e9e.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9, ou que tu n'interviens plus pour contr\u00f4ler son fonctionnement.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches, sans que tu v\u00e9rifies ou que tu critiques ce qu'elle fait.",
  },
  {
    img1: "img_Time.png",
    title1: "Temps",
    desc1: "L'usage de l'IA est motiv\u00e9 par le gain de temps : certaines t\u00e2ches sont faites automatiquement et sans effort.",
    img2: "img_inclusion.png",
    title2: "\u00c9tayage et inclusion",
    desc2: "En s'appuyant sur un profil personnalis\u00e9, l'IA est capable d'adapter ses r\u00e9ponses \u00e0 l'utilisateur. Elle peut aussi compenser certaines de ses difficult\u00e9s.",
  },
  {
    img1: "img_Robbery.png",
    title1: "Pillage",
    desc1: "L'utilisation de l'IA ne respecte pas les droits des auteurs. M\u00eame si elle transforme ces sources, elle les utilise sans citer et sans r\u00e9tribuer les cr\u00e9ateurs.",
    img2: "img_Time.png",
    title2: "Respect des droits",
    desc2: "Tu es conscient que l'IA peut utiliser des sources prot\u00e9g\u00e9es par des droits d'auteur. Pour toi, c'est un aspect important.",
  },
  {
    img1: "img_Frugalite.png",
    title1: "Frugalit\u00e9 / \u00e9conomie",
    desc1: "Tes choix montrent une volont\u00e9 de ne pas gaspiller les ressources naturelles.",
    img2: "img_Gaspillage.png",
    title2: "Gaspillage",
    desc2: "Ta pratique r\u00e9p\u00e9t\u00e9e ou maladroite de l'IA consomme beaucoup de ressources naturelles et impacte l'environnement.",
  },
  {
    img1: "img_BoiteNoire.png",
    title1: "Bo\u00eete noire",
    desc1: "Tu ne sais pas comment fonctionnent les outils d'IA. Ces outils sont comme des \"bo\u00eetes noires\" qui agissent de fa\u00e7on un peu magique.",
    img2: "img_Tsprence.png",
    title2: "Transparence de fonctionnement",
    desc2: "Pour toi, il est essentiel que tu comprennes le fonctionnement, pour que tu utilises ces outils de fa\u00e7on r\u00e9fl\u00e9chie.",
  },
  {
    img1: "img_equality.png",
    title1: "\u00c9galitaire",
    desc1: "Tu es d'accord pour dire que l'IA doit s'adresser \u00e0 tout le monde. Elle doit s'adapter aux minorit\u00e9s, aux personnes en difficult\u00e9.",
    img2: "img_Inegalite.png",
    title2: "In\u00e9galitaire",
    desc2: "On ne pourra pas faire en sorte que l'IA soit utilis\u00e9e par tout le monde de la m\u00eame mani\u00e8re. Tant pis si \u00e7a doit cr\u00e9er ou empirer les in\u00e9galit\u00e9s.",
  },
  {
    img1: "img_datacloud.png",
    title1: "S\u00e9curit\u00e9 des donn\u00e9es",
    desc1: "Les donn\u00e9es d'entra\u00eenement ou d'utilisation de l'IA doivent \u00eatre v\u00e9rifi\u00e9es. On r\u00e9duit ainsi le risque d'erreur ou l'usage de donn\u00e9es non autoris\u00e9es.",
    img2: "img_data.png",
    title2: "Open Data",
    desc2: "Peu importe les donn\u00e9es utilis\u00e9es par l'IA. Plus il y en a, plus les r\u00e9sultats seront pertinents, selon toi.",
  },
  {
    img1: "img_CultureRespect.png",
    title1: "Respect des cultures",
    desc1: "Tu sais que l'IA favorise certaines cultures. Elle poss\u00e8de des biais culturels. Tu aimerais qu'elle prenne en compte davantage de cultures.",
    img2: "img_CultureHegemonie.png",
    title2: "Culture h\u00e9g\u00e9monique",
    desc2: "L'IA se nourrit surtout des cultures de langue anglaise. Il faut accepter que certaines cultures soient majoritaires.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches sans que tu v\u00e9rifies ce qu'elle fait.",
  },
];
