export const PARCOURS = [
  { id: "donnees", label: "Des données sensibles", color: "#f59e0b", cards: [18,25,28,29,35,38,50,61,65,68,76,77,78,81,98] },
  { id: "roles", label: "Des rôles pour l'IA", color: "#10b981", cards: [1,2,3,4,5,6,7,25,29,31,59,62,71,83,84,85,86,93,98] },
  { id: "transparence", label: "Un peu de transparence", color: "#ef4444", cards: [11,17,27,34,45,56] },
  { id: "scribe", label: "L'IA scribe", color: "#8b5cf6", cards: [16,17,20,57,58,89,90,91,95,99,100] },
  { id: "competences", label: "Des compétences à ne pas oublier", color: "#06b6d4", cards: [6,8,14,15,16,20,26,36,46,58,60,66,70,72,80,82,85,87,88,91,96,97,99] },
  { id: "societe", label: "Impact sur la société", color: "#ec4899", cards: [10,24,30,32,33,44,49,55,59,62,66,76,77] },
  { id: "planete", label: "Impact sur la planète", color: "#22c55e", cards: [8,12,13,19,35,51,52,53,54,55,56,67,92] },
  { id: "encadrer", label: "Soutenir et encadrer", color: "#f97316", cards: [1,2,4,6,26,28,31,47,48,57,64,79,80,95] },
  { id: "veracite", label: "Ce résultat est-il juste et vrai ?", color: "#3b82f6", cards: [5,9,14,22,37,39,48,63,64,69,73,74,75,79,100] },
  { id: "prompt", label: "Prompter promptement", color: "#d946ef", cards: [21,22,23,25,70] },
  { id: "esprit_critique", label: "Croire ou vérifier ?", color: "#84cc16", cards: [69,70,71,72,73,74,75,84,94] },
  { id: "vie_etablissement", label: "Au-delà des cours", color: "#0ea5e9", cards: [46,61,82,86,87,88,89,90,92,93,94,96,97] },
]


export const questions = [
  { id: 1, titre: "IA mentor", situation: "J'ai entendu parler d'une IA mentor : elle me sert de coach, en me donnant des commentaires au fur et à mesure de mon travail.", altA: "Oui, c'est plus facile et plus accessible qu'un prof qui a rarement le temps de me guider.", altB: "Non, même si j'ai besoin d'un coach, je préfère tracer mon chemin par mes propres moyens." },
  { id: 2, titre: "IA tuteur", situation: "J'ai entendu parler d'une IA tuteur : elle prendrait en charge mon apprentissage, à la place du prof.", altA: "Pourquoi pas, le prof n'est pas toujours disponible pour m'aider.", altB: "Surtout pas, ça reste une machine, elle ne me connaît pas et elle demande trop de données personnelles." },
  { id: 3, titre: "IA équipière", situation: "J'ai entendu parler d'une IA équipière : dans un travail de groupe, elle fait équipe avec nous en donnant son avis.", altA: "Oui, ce serait pas mal d'avoir un autre avis, même si c'est celui d'une machine.", altB: "Non, c'est déjà difficile de s'entendre entre nous, alors avec une voix en plus…" },
  { id: 4, titre: "IA coach", situation: "J'ai entendu parler d'une IA coach : elle me pose des questions sur ce que j'ai fait, sur ce que je pense avoir réussi et elle me donne des conseils pour progresser.", altA: "Oui, j'ai toujours rêvé d'avoir une voix qui m'aiderait à savoir où j'en suis !", altB: "Non, ça va pas du tout ! Elle va collecter plein de données sur mon travail. C'est trop personnel pour lui laisser tout ça !" },
  { id: 5, titre: "IA simulateur", situation: "J’utilise une IA-simulateur.Elle reproduit une situation, comme si c'était réel. Ça fait jeu vidéo, et c'est motivant.", altA: "Oui, c'est quand même mieux qu'une étude de cas avec plein de questions.", altB: "Non, une simulation reste une simulation : elle ne représente pas assez bien ce qu'on voit dans la vraie vie." },
  { id: 6, titre: "IA outil", situation: "J’utilise une IA-outil. Elle est spécialisée dans une tâche précise (programmation, travail sur des textes, génération d'images…).", altA: "Oui,  elle sera plus efficace sur ce qu'on cherche à faire.", altB: "Non, on a besoin de travailler ces compétences. Avec l'IA, on ne pourra jamais les entraîner correctement." },
  { id: 7, titre: "IA soutien", situation: "Cette IA est là pour aider les élèves qui ont des difficultés bien identifiées. Elle leur sert de \"béquille\" pour faire ce qu'ils ne seraient pas capables de faire.", altA: "Oui, sans IA, il est bien difficile de leur apporter de l'aide.", altB: "Non, ce n'est pas juste pour les autres qui ne bénéficieront pas de cette IA." },
  { id: 8, titre: "Recherche documentaire", situation: "Pour une recherche documentaire générale, j’utilise une IA générative, c'est bien plus rapide !", altA: "Une IA générative, comme cela, on passe plus rapidement au travail de compréhension, de liens, de traitement des données", altB: "Un moteur de recherche, mais ça demande de critiquer les résultats et de  sélectioner les informations utiles, avec leurs sources." },
  { id: 9, titre: "Un résultat préoccupant", situation: "J'ai utilisé l'IA, mais je trouve que le résultat n'est pas à la hauteur de ce que j'espérais.", altA: "Je retente, jusqu'à ce que le résultat soit satisfaisant.", altB: "Je retente mais pas trop, il paraît que ça consomme beaucoup d'énergie et de ressources." },
  { id: 10, titre: "Justice ?", situation: "J'ai fait seul mon devoir à la maison et je l'ai rendu, mais j'ai une moins bonne note que d'autres qui ont utilisé l'IA.", altA: "Je réagis. Il faut que les profs soient capables de gérer cette injustice.", altB: "Je ne fais rien. Ça se reproduira, et ça ne va pas m'encourager à continuer comme ça." },
  { id: 11, titre: "Confiance ?", situation: "J'ai terminé d'écrire un texte. Le prof se montre méfiant. Il pense que j'ai utilisé une IA car c'est meilleur que d'habitude.", altA: "Je continuerai à faire comme ça. Je n'ai rien à me reprocher.", altB: "J'utilise un site qui permet de vérifier si mon texte est ressemblant à ce qu'une IA pourrait produire." },
  { id: 12, titre: "Gaspillage", situation: "J'ai testé l'outil ComparIA. J'ai vu toutes les ressources que j'ai utilisées pour mes demandes à l'IA. C'est énorme…", altA: "Tant pis, si je me préoccupe de cela, je ne ferai plus grand-chose.", altB: "Quand même, ça me gêne. Je vais essayer de trouver des pratiques un peu plus responsables." },
  { id: 13, titre: "Grand ou petit modèle ?", situation: "Je privilégie les grands modèles d’IA (Gemini, ChatGPT, Mistral, Claude…), plutôt que les modèles hébergés en local dans mon établissement.", altA: "Oui, j'ai l'habitude avec ces outils. C'est plus simple.", altB: "Non, il paraît que les modèles en local sont plus petits, moins consommateurs, mais ils sont moins accessibles." },
  { id: 14, titre: "Où se trouve la source ?", situation: "J'ai fait une recherche avec l'IA, mais on m'a demandé les sources. Et l'IA que j'utilise ne me la donne pas.", altA: "Tant pis, on fera sans, ce n'est pas si important.", altB: "Quand même, je vais utiliser un moteur de recherche ou des livres, ça existe encore." },
  { id: 15, titre: "Les deux à la fois ?", situation: "J'ai utilisé un moteur de recherche, et j'ai vu qu'il proposait d'utiliser une IA pour avoir un résumé des résultats.", altA: "C'est parfait, je ne suis plus obligé de cliquer sur les liens et de lire les résultats !", altB: "C'est limité, je ne peux même plus faire mon choix d'informations moi-même !" },
  { id: 16, titre: "Aide à l'écriture", situation: "Je dois écrire un texte. Quel travail vais-je demander à l'IA ?", altA: "Quitte à faire, tout le travail à ma place.", altB: "De la reformulation du texte que j'ai écrit moi-même." },
  { id: 17, titre: "Transparence", situation: "Je dois rendre un texte. Je l'ai fait en partie avec de l'IA.", altA: "Je rends mon travail, sans aucune précision.", altB: "Je copie et colle ma demande à l'IA, je prof saura comment je l'ai utilisée." },
  { id: 18, titre: "Nourrir une IA", situation: "Je voudrais que l'IA retravaille le fichier que j'ai créé (un exposé, un texte, peu importe).", altA: "Aucun problème, même si l'IA va conserver mon fichier et le réutiliser plus tard.", altB: "Pas question de la laisser utiliser ce que j'ai fait. C'est moi le propriétaire." },
  { id: 19, titre: "Calculatrice de luxe", situation: "Pour faire un calcul, je demande directement à l'IA. C'est moins galère que de sortir la calculatrice.", altA: "Oui, ça permet d'aller plus vite.", altB: "Non, inutile d'utiliser un outil aussi puissant et consommateur pour un truc aussi facile." },
  { id: 20, titre: "Qui fera le résumé ?", situation: "Je dois faire un exposé pour résumer tout un sujet.", altA: "Je demande à l'IA de faire la synthèse de ce que j'ai trouvé. Rapide et efficace.", altB: "Je fais la synthèse moi-même, sinon, je ne comprendrai rien au sujet." },
  { id: 21, titre: "Ultra rapide", situation: "Je dois me dépêcher. J'ai une demande à faire à l'IA.", altA: "Je fais la demande comme sur un moteur de recherche, quitte à l'améliorer par la suite.", altB: "Je prends le temps de bien faire ma première demande. Ça m'évitera d'en faire d'autres pour préciser la réponse." },
  { id: 22, titre: "Doutes", situation: "J'ai fait une recherche avec l'IA et j'ai des doutes sur les résultats.", altA: "Je compare avec les résultats d'autres IA.", altB: "Je reste sur ces résultats. D'autres IA ne m'apporteront rien de plus." },
  { id: 23, titre: "En une fois ou en plein de fois", situation: "Je fais une demande à l'IA. Quelle sera la stratégie que je vais adopter ?", altA: "Je le fais en plusieurs fois, en précisant mes demandes.", altB: "Je travaille ma demande pour avoir un résultat acceptable rapidement." },
  { id: 24, titre: "Théorie du remplacement", situation: "J’ai entendu parler de la théorie du remplacement. Il paraît que de nombreux emplois seront détruits car remplacés par l’IA", altA: "Même pas peur. On trouvera d'autres emplois dans le futur, on s'adaptera.", altB: "ça me stresse. Je ne vais pas commencer à me former à un métier qui pourrait disparaître." },
  { id: 25, titre: "Un peu d'entraînement", situation: "Je demande à l'IA de créer des exercices pour que je puisse réviser. Mais pour être efficace…", altA: "Je lui donne uniquement les cours de mes profs.", altB: "Je lui demande de chercher où elle veut, sans la restreindre." },
  { id: 26, titre: "Intuition de départ", situation: "J'ai un exposé à faire. Je ne sais pas comment commencer.", altA: "Je demande à l'IA de me donner le départ. Je continuerai moi-même ensuite.", altB: "Je veux commencer moi-même, sinon, je ne maîtrise pas le sujet. L'IA pourra m'aider plus tard, pour d'autres tâches." },
  { id: 27, titre: "Absence de cadre", situation: "Dans mon établissement scolaire, il n'y a pas de règle sur l'utilisation de l'IA. Du coup, on ne sait pas si on peut l'utiliser ou pas.", altA: "Je préfère éviter au maximum de l'utiliser, ça pourrait toujours m'être reproché.", altB: "Je l'utilise quand même, s'il n'y a pas de cadre, c'est qu'il n'y a pas de problème." },
  { id: 28, titre: "Coaching par l'IA", situation: "J'ai des difficultés et on me propose de tester une IA qui va me coacher.", altA: "Oui, ça peut toujours m'aider.", altB: "Non, il lui faudra plein de données sur moi, et je n'ai pas envie de ça." },
  { id: 29, titre: "L'IA va m'orienter", situation: "Une IA conseillère d'orientation est en expérimentation. Elle serait capable de m'orienter, et de participer aux procédures d'admission.", altA: "Oui, ça ne sera pas pire que les jurys qui ne sont pas toujours justes.", altB: "Non, c'est mon avenir et mes données, je ne veux pas qu'une IA puisse influencer mon destin." },
  { id: 30, titre: "Une IA magique", situation: "Une IA agentique est capable de me donner des réponses en faisant plusieurs tâches l'une après l'autre. C'est pratique : je donne ce qu'il y a à faire, et je récupère le résultat !", altA: "Oui, c'est tellement plus rapide que de décomposer toutes ces tâches !", altB: "Non, je n'ai aucun moyen de vérifier et de valider ce qu'elle fait, et de corriger s'il y a besoin." },
  { id: 31, titre: "Chatbot motivationnel", situation: "On m'a proposé de tester un chatbot motivationnel. Je parle avec lui quand je suis démotivé, et il m'encourage.", altA: "Oui, ça aide quand on ne trouve personne pour se rebooster.", altB: "Non, ça reste une machine programmée, pas un ami ou un psy." },
  { id: 32, titre: "IA sélective 1", situation: "Dans ma classe, on nous propose des comptes pour utiliser une IA pro, mais il n'y a pas assez de comptes pour tout le monde.", altA: "On les réserve pour les personnes les plus bosseuses, pour qu'elles continuent à performer.", altB: "On les réserve aux personnes en difficulté, pour les aider à s'améliorer." },
  { id: 33, titre: "IA sélective 2", situation: "Dans ma classe, on nous propose des comptes pour utiliser une IA pro, mais il n'y a pas assez de comptes pour tout le monde.", altA: "On les réserve pour une partie de la classe, tant pis pour l'égalité.", altB: "Soit c'est l'IA pour tout le monde, soit c'est l'IA pour personne." },
  { id: 34, titre: "Trop de triche !", situation: "Dans ma classe, il y a trop d'élèves qui utilisent l'iA pour les évals. Les profs s'en rendent compte et cherchent des solutions.", altA: "Ils devraient tout interdire et renforcer les moyens pour le contrôler.", altB: "Ils devraient nous encourager à dire quand et comment on utilise l'IA, notamment pour les DM." },
  { id: 35, titre: "Illustrations", situation: "J'ai besoin d'images pour illustrer un exposé.", altA: "Je demande à une IA générative pour les créer rapidement, selon mes instructions.", altB: "Je demande à un moteur de recherche, surtout que je ne sais pas exactement ce que je voudrais." },
  { id: 36, titre: "Exposé", situation: "Je dois faire un exposé. Je ne peux pas le faire seul, il me faut de l'aide.", altA: "Je préfère l'IA, c'est plus rapide et pratique.", altB: "Je préfère le groupe de travail, c'est plus convivial." },
  { id: 37, titre: "Supériorité", situation: "Je fais une  demande à une IA américaine, pour savoir quels sont les meilleurs scientifiques de l'histoire. Elle me sort 10 noms de savants blancs, parlant anglais, tous des hommes.", altA: "C'est comme ça, c'est possible que ce soit ces personnes qui ont marqué l'histoire des sciences.", altB: "Il doit y avoir un biais, puisque c'est une IA américaine." },
  { id: 38, titre: "Mettre les mains dans le cambouis", situation: "On me propose un cours sur le fonctionnement des IA : les algorithmes, les modèles d'entraînement, etc.", altA: "Inutile. Je ne veux pas devenir informaticien !", altB: "Utile, j'ai besoin de savoir comment ces outils marchent pour mieux comprendre leurs résultats." },
  { id: 39, titre: "Bleu, blanc, rouge ?", situation: "J'ai le choix entre deux modèles d'IA, qui ont une seule différence : leur nationalité.", altA: "Je préfère le modèle français, même s'il était un peu plus cher.", altB: "Je préfère le modèle américain ou choinois, peut-être plus performant et plus utilisé dans le monde." },
  { id: 40, titre: "Une IA qui signe à ma place ?", situation: "Le collège organise un concours d'écriture. Je peux soumettre un texte largement écrit avec une IA, sous mon nom, ou un texte plus modeste mais entièrement de moi.", altA: "Je soumets le texte assisté par IA. Le règlement ne l'interdit pas explicitement, et le résultat est bien meilleur.", altB: "Je soumets mon propre texte, plus simple. Un concours d'écriture doit récompenser ce qu'on sait vraiment faire soi-même." },
  { id: 41, titre: "Choisir une option « IA-proof » ?", situation: "Pour choisir mes options au lycée, on me conseille de privilégier des matières jugées résistantes à l'IA plutôt que celles que j'aime vraiment.", altA: "Je choisis selon ce conseil. Autant anticiper un monde du travail transformé par l'IA.", altB: "Je choisis selon mes goûts, sans trop y penser. Personne ne sait vraiment ce qui sera épargné par l'IA dans dix ans." },
  { id: 42, titre: "Une IA pour suivre en cas de handicap ?", situation: "Un élève malentendant de ma classe peut utiliser une IA qui sous-titre en direct les cours, mais elle capte aussi parfois des bribes de conversations privées entre élèves.", altA: "Je trouve que c'est un compromis acceptable. L'accessibilité pour lui compte plus que ce risque limité.", altB: "Ça me gêne. Même pour une bonne cause, je n'aime pas savoir que nos conversations peuvent être captées." },
  { id: 43, titre: "Suivre la tendance ou pas ?", situation: "Tous mes amis utilisent une IA pour s'aider à un jeu-concours de culture générale entre classes, ce qui n'est pas franchement dans l'esprit du jeu.", altA: "Je fais pareil qu'eux. Si tout le monde le fait, refuser me désavantage sans rien changer au fond.", altB: "Je refuse de le faire. Même si ça ne change rien au résultat final, je préfère jouer honnêtement." },
  { id: 44, titre: "Gratuit ou payant ?", situation: "Pour m'aider dans mes devoirs, j'ai le choix entre la version gratuite d'une IA (limitée, parfois moins fiable) et un abonnement payant, plus précis et plus rapide.", altA: "Je reste sur la version gratuite. Ça marche déjà bien pour l'essentiel, et tout le monde peut y accéder de la même façon.", altB: "Je prends l'abonnement payant. Les réponses sont plus fiables, ça vaut le coût si j'en ai les moyens." },
  { id: 45, titre: "Elle explique ou elle répond ?", situation: "J'utilise une IA pour comprendre un exercice de maths. Certaines expliquent leur raisonnement étape par étape, d'autres donnent directement le résultat.", altA: "Je préfère celle qui explique son raisonnement. C'est plus long à lire, mais je comprends vraiment la méthode.", altB: "Je préfère celle qui donne directement la réponse. C'est plus rapide, et je peux avancer plus vite dans mes devoirs." },
  { id: 46, titre: "Le manuel enrichi", situation: "Mon collège propose de remplacer un manuel papier par une version numérique enrichie par l'IA, avec exercices interactifs et corrections automatiques.", altA: "Je choisis le manuel numérique. C'est plus ludique et interactif, ça donne envie de travailler.", altB: "Je garde le manuel papier. C'est peut-être moins amusant, mais je retiens mieux en écrivant et en cherchant moi-même." },
  { id: 47, titre: "Une journée sans IA", situation: "Mon établissement instaure un jour par semaine sans écran ni IA, pour tous les élèves.", altA: "Je trouve ça bien. Ça m'oblige à mobiliser mes propres compétences, même si c'est parfois frustrant.", altB: "Je trouve ça excessif. Autant utiliser les outils qu'on a à disposition tous les jours, pas qu'un jour sur sept." },
  { id: 48, titre: "Un oral de contrôle", situation: "J'ai rendu un devoir à la maison. Le prof, qui pense que je l'ai fait avec une IA sans le dire, me propose un oral de contrôle pour vérifier que je maîtrise le sujet.", altA: "Je passe l'oral tranquillement. Si j'ai vraiment compris ce que j'ai rendu, ça ne me fait pas peur.", altB: "Je trouve ça injuste d'être soupçonné sans preuve, même si en vrai j'ai un peu utilisé l'IA sans le dire." },
  { id: 49, titre: "Un camarade sans accès", situation: "Un camarade de classe n'a pas Internet chez lui et ne peut donc pas utiliser l'IA pour ses devoirs, contrairement à moi.", altA: "Je lui propose de venir travailler chez moi ou de lui montrer comment je m'en sers, pour qu'on soit à égalité.", altB: "Je continue comme d'habitude. Ce n'est pas à moi de compenser les inégalités d'accès à Internet." },
  { id: 50, titre: "L'outil du kiosque ou l'outil perso ?", situation: "Mon collège met à disposition un outil d'IA labellisé, hébergé en France, mais un peu plus lent. J'ai aussi accès chez moi à un outil grand public, plus rapide et plus puissant.", altA: "J'utilise l'outil du collège. Il est peut-être moins performant, mais mes données restent maîtrisées et il a été vérifié.", altB: "Je préfère l'outil que je connais déjà à la maison. Il est plus rapide et je n'ai pas à apprendre un nouvel outil." },
  { id: 51, titre: "Petit modèle sobre ou grand modèle puissant ?", situation: "Pour un exercice simple, je peux utiliser un petit modèle d'IA, plus sobre en énergie, ou un grand modèle, plus lourd mais parfois plus précis.", altA: "Je choisis le petit modèle. Pour une tâche simple, ça suffit largement et ça consomme moins.", altB: "Je prends le grand modèle par sécurité. Je préfère être sûr d'avoir la meilleure réponse possible." },
  { id: 52, titre: "Un téléphone plus récent pour l'IA embarquée ?", situation: "Mon téléphone actuel ne peut pas faire tourner les nouvelles fonctions d'IA intégrées. Mes parents me proposent d'en racheter un plus récent.", altA: "Je garde mon téléphone actuel. Je peux toujours utiliser l'IA via une appli ou un site, pas besoin de racheter.", altB: "Je change de téléphone. Autant profiter des nouvelles fonctions si on en a l'occasion." },
  { id: 53, titre: "Vidéo générée ou texte pour mon exposé ?", situation: "Pour illustrer mon exposé, je peux demander à une IA de générer une courte vidéo, plus impressionnante mais très gourmande en ressources, ou me contenter d'un texte et d'images fixes.", altA: "Je reste sur le texte et les images. C'est moins spectaculaire, mais ça suffit pour être compris.", altB: "Je génère la vidéo. Ça rend l'exposé plus vivant, et ce n'est qu'une fois." },
  { id: 54, titre: "Un accès illimité, alors j'en profite ?", situation: "Depuis que mon abonnement IA est illimité et gratuit, je m'en sers pour absolument tout, même des questions que je pourrais résoudre seul en trente secondes.", altA: "Je me limite quand même aux vraies questions utiles. Ce n'est pas parce que c'est gratuit qu'il faut en abuser.", altB: "Je m'en sers pour tout, tant que c'est illimité. Autant profiter de ce que ça permet." },
  { id: 55, titre: "Un centre de données près de chez moi", situation: "Un centre de données va être construit près de ma ville. Il devrait créer des emplois, mais il va aussi consommer beaucoup d'eau et d'électricité localement.", altA: "Je soutiens le projet. Ça crée de l'activité économique, et il faut bien héberger ces services quelque part.", altB: "Je m'inquiète pour les ressources locales : l'eau et l'électricité risquent de manquer pour les habitants." },
  { id: 56, titre: "Une IA muette sur sa consommation", situation: "L'IA que j'utilise ne dit jamais combien elle consomme d'énergie ou d'eau pour répondre à mes demandes. Une autre, moins connue, affiche une estimation à chaque réponse.", altA: "Je choisis celle qui affiche sa consommation, même si elle est moins pratique à utiliser au quotidien.", altB: "Je reste sur celle que je connais. Ce chiffre ne changerait de toute façon pas grand-chose à mes usages." },
  { id: 57, titre: "Une IA qui résume nos décisions", situation: "Au conseil de vie collégienne, on propose d'utiliser une IA pour résumer les débats et proposer une synthèse des décisions à prendre.", altA: "Je trouve ça utile. Ça permet de ne rien oublier et de gagner du temps sur la rédaction.", altB: "Je préfère qu'on rédige nous-mêmes. Une synthèse automatique risque de déformer ce qu'on a vraiment dit." },
  { id: 58, titre: "Une IA prend des notes à ma place", situation: "Pendant les réunions d'un club dont je suis responsable, je peux laisser une IA transcrire et résumer automatiquement, plutôt que de prendre des notes moi-même.", altA: "Je laisse l'IA transcrire. Je peux me concentrer entièrement sur la discussion pendant la réunion.", altB: "Je prends mes notes moi-même. Ça m'oblige à vraiment être attentif à ce qui compte." },
  { id: 59, titre: "Une décision qui me concerne, avec l'aide d'une IA", situation: "Pour m'aider à choisir mon orientation, le CIO utilise un outil d'IA qui analyse mon profil et propose des pistes, toujours validées ensuite par un conseiller humain.", altA: "Je trouve ça rassurant. L'IA élargit les pistes possibles, et un humain valide quand même à la fin.", altB: "Ça me met mal à l'aise. Je préfère que ce soit une personne qui réfléchisse à mon profil depuis le début." },
  { id: 60, titre: "Se former vite, quitte à moins bien ?", situation: "On me propose une formation accélérée à l'IA en une demi-journée, plutôt qu'un module plus complet étalé sur plusieurs semaines.", altA: "Je prends la formation courte. Ça me donne au moins une base, et je pourrai compléter plus tard si besoin.", altB: "Je préfère attendre le module complet. Une demi-journée ne suffit pas pour vraiment comprendre les enjeux." },
  { id: 61, titre: "Construire notre propre outil ou en acheter un ?", situation: "Mon collège hésite entre développer son propre outil d'IA avec les élèves volontaires, ou acheter un abonnement à une solution déjà toute prête.", altA: "Je préfère qu'on achète une solution toute prête. C'est plus fiable et plus rapide à mettre en place.", altB: "Je préfère qu'on construise notre outil. On comprend mieux comment ça marche, même si c'est plus long." },
  { id: 62, titre: "Un ami virtuel pour mes soucis", situation: "Quand j'ai un souci personnel, je peux en parler tout de suite à une IA disponible immédiatement, ou attendre de pouvoir en parler à quelqu'un de mon entourage.", altA: "Je préfère en parler tout de suite à l'IA. Au moins je ne reste pas seul avec mes questions en attendant.", altB: "J'attends d'en parler à quelqu'un que je connais. Une vraie personne comprend mieux ce que je vis." },
  { id: 63, titre: "Signalé à tort par un détecteur d'IA", situation: "Un logiciel censé détecter les textes écrits par IA signale mon devoir comme suspect, alors que je l'ai entièrement rédigé moi-même.", altA: "Je conteste calmement auprès du prof, en expliquant ma méthode de travail, même si ça prend du temps.", altB: "Je laisse couler. Protester risque de me faire passer pour quelqu'un qui a quelque chose à cacher." },
  { id: 64, titre: "Un devoir surveillé par IA", situation: "Pour un devoir à la maison noté, l'établissement propose d'utiliser un logiciel qui surveille mon écran pendant que je compose, pour vérifier que je n'utilise pas d'IA.", altA: "J'accepte la surveillance. Ça garantit que la note reflète vraiment mon propre travail.", altB: "Ça me dérange d'être observé comme ça. Je préfère qu'on me fasse confiance ou qu'on évalue autrement." },
  { id: 65, titre: "Partager mes travaux pour entraîner une IA", situation: "Une IA éducative gratuite propose d'être encore meilleure si les élèves acceptent que leurs travaux et corrections servent à l'entraîner.", altA: "J'accepte. Si ça permet d'améliorer l'outil pour tout le monde, ça me semble un juste échange.", altB: "Je refuse. Mon travail m'appartient, je ne veux pas qu'il serve à entraîner un produit commercial." },
  { id: 66, titre: "Traduire ou apprendre la langue ?", situation: "Un nouvel élève ne parle pas encore bien français. Je peux utiliser une IA pour traduire nos échanges en direct, ou essayer de communiquer avec les quelques mots qu'il connaît déjà.", altA: "J'utilise l'IA pour traduire. On peut vraiment se comprendre tout de suite, sans que ça prenne des mois.", altB: "J'essaie de communiquer autrement, avec des gestes et le peu de mots qu'il connaît. C'est plus lent, mais on progresse ensemble." },
  { id: 67, titre: "Se chauffer grâce aux serveurs IA", situation: "Le centre de données voisin propose de récupérer la chaleur produite par ses serveurs pour chauffer une partie de mon lycée, gratuitement, en échange d'un partenariat de long terme avec l'exploitant.", altA: "Je trouve que c'est une bonne idée. Autant récupérer une chaleur qui serait perdue de toute façon.", altB: "Ça me gêne qu'on devienne dépendant d'un partenariat avec une entreprise dont l'activité pollue par ailleurs." },
  { id: 68, titre: "IA sur mon appareil ou dans le cloud ?", situation: "Pour utiliser l'IA sans connexion et sans envoyer mes données à l'extérieur, mon téléphone propose une version installée directement dessus, moins puissante qu'une version en ligne.", altA: "Je choisis la version installée sur mon téléphone. Mes données ne sortent pas de l'appareil, c'est plus rassurant.", altB: "Je choisis la version en ligne. Elle est plus puissante, et je fais confiance au service que j'utilise." },
  { id: 69, titre: "Elle cite une source, mais dit-elle vrai ?", situation: "Une IA me donne une réponse avec une source qui a l'air sérieuse. En vérifiant, je trouve bien la source, mais elle ne dit pas exactement ce que l'IA prétend.", altA: "Je fais confiance à la réponse de l'IA. La source existe, ça me suffit comme preuve.", altB: "Je me méfie et je signale l'écart. Une source qui existe ne veut pas dire que l'IA l'a bien comprise." },
  { id: 70, titre: "Chercher les mots ou chercher la réponse ?", situation: "Je bloque sur un sujet de recherche parce que je ne trouve pas les bons mots-clés à taper dans un moteur de recherche. Une IA peut soit me donner directement la réponse toute faite, soit juste m'aider à trouver des mots-clés à utiliser ensuite moi-même.", altA: "Je lui demande directement la réponse. C'est plus simple et plus rapide.", altB: "Je lui demande juste des mots-clés, puis je fais ma propre recherche avec de vraies sources." },
  { id: 71, titre: "Elle dit bonjour, je réponds ?", situation: "Certains de mes camarades disent bonjour et merci à l'IA, comme s'ils parlaient à une vraie personne. D'autres trouvent que ça n'a aucun sens puisque ce n'est qu'un programme.", altA: "Je fais pareil, par politesse. Ça ne coûte rien et ça garde de bonnes habitudes.", altB: "Je ne le fais pas. Pour moi, ça entretient l'idée que l'IA comprend ou ressent quelque chose, ce qui n'est pas le cas." },
  { id: 72, titre: "J'ai la réponse, ai-je vraiment compris ?", situation: "Après avoir utilisé une IA pour un exercice difficile, j'ai l'impression d'avoir tout compris. Mais je me demande si je saurais refaire l'exercice tout seul, sans elle.", altA: "Je passe à la suite. Si la réponse est juste et que je comprends l'explication en la lisant, c'est suffisant.", altB: "Je referme l'IA et j'essaie de refaire l'exercice seul, pour vérifier que j'ai vraiment compris et pas juste lu." },
  { id: 73, titre: "Je vérifie, ou je fais confiance ?", situation: "La plupart du temps, je me dis que je devrais vérifier les réponses de l'IA, mais en pratique, je les accepte presque toujours telles quelles.", altA: "Je continue comme ça. Vérifier systématiquement prendrait un temps que je n'ai pas à chaque fois.", altB: "Je décide de vraiment vérifier, au moins une fois sur deux, même si c'est plus long." },
  { id: 74, titre: "Elle hallucine, mais elle a l'air sûre d'elle", situation: "Une IA me donne une réponse fausse, mais formulée avec la même assurance que si elle était vraie. Rien dans le ton ne permet de deviner qu'elle se trompe.", altA: "Je fais quand même confiance au ton assuré. Si elle se trompait, ça se sentirait plus.", altB: "Je me méfie du ton assuré justement. Une IA parle pareil, qu'elle ait raison ou tort." },
  { id: 75, titre: "Une synthèse ou des sources qui se contredisent ?", situation: "Pour mon exposé, je peux demander à l'IA une synthèse toute faite du sujet, ou aller chercher plusieurs sources qui ne disent pas exactement la même chose, et me faire mon propre avis.", altA: "Je prends la synthèse de l'IA. C'est cohérent, bien écrit, et ça m'évite de me perdre dans des sources contradictoires.", altB: "Je vais chercher plusieurs sources, même contradictoires. Ça me permet de comprendre qu'il y a débat, pas une seule vérité." },
  { id: 76, titre: "Un tableau de bord sur mon risque de décrochage", situation: "Le collège utilise un outil d'IA qui repère les élèves à risque de décrochage à partir de mes absences, mes notes et mes résultats, pour alerter plus tôt les adultes qui peuvent m'aider.", altA: "Je trouve ça rassurant. Si je traverse une mauvaise période, quelqu'un peut le remarquer avant que ça s'aggrave.", altB: "Ça me met mal à l'aise. Je n'ai jamais donné mon accord pour que mes données soient analysées comme ça." },
  { id: 77, titre: "Partager mes fiches de révision dans un pot commun", situation: "Une plateforme propose de mettre en commun les fiches de révision générées ou corrigées avec l'IA par tous les élèves d'un même niveau, accessibles à tous gratuitement.", altA: "Je partage mes fiches. Si ça aide d'autres élèves, tant mieux, et je profite aussi de celles des autres.", altB: "Je garde mes fiches pour moi. J'ai mis du temps à les préparer, ce n'est pas à moi de les offrir à tout le monde." },
  { id: 78, titre: "Une IA qui a beaucoup appris de moi", situation: "J'utilise depuis un an la même IA pour m'aider dans mes devoirs. Elle connaît maintenant très bien ma façon de travailler et anticipe mes questions.", altA: "Je trouve ça pratique. Elle me comprend de mieux en mieux, comme un vrai assistant personnel.", altB: "Ça m'inquiète un peu. Je ne sais pas exactement ce qu'elle garde en mémoire sur moi ni pour combien de temps." },
  { id: 79, titre: "Un devoir de groupe avec ou sans IA imposée", situation: "Pour un travail de groupe, le prof impose que personne n'utilise l'IA, mais un camarade du groupe le fait quand même en cachette, et le rendu final en profite.", altA: "Je le signale au prof. La règle vaut pour tout le groupe, et il n'est pas juste que le nôtre bénéficie d'un avantage caché.", altB: "Je ne dis rien. Ce n'est pas à moi de rapporter un camarade, et le résultat du groupe est meilleur comme ça." },
  { id: 80, titre: "Une pause numérique collective", situation: "Ma classe propose de tenter, ensemble, une semaine complète sans aucun usage d'IA, y compris pour les devoirs à la maison, pour voir ce que ça change.", altA: "Je participe avec enthousiasme. Ça peut être intéressant de comparer, même si c'est contraignant.", altB: "Je participe, mais à contrecœur. Ça me semble artificiel de s'interdire un outil qu'on utilisera de toute façon après." },
  { id: 81, titre: "Une appli qui suit mes progrès sur le long terme", situation: "Une appli d'apprentissage garde en mémoire mes progrès sur plusieurs années et ajuste les exercices en fonction de tout mon historique scolaire, y compris mes anciens échecs.", altA: "Je trouve ça utile. Elle voit mieux que quiconque où j'ai vraiment progressé et où je bute encore.", altB: "Ça me gêne qu'elle garde en mémoire mes anciens échecs indéfiniment. J'aimerais pouvoir tourner la page." },
  { id: 82, titre: "Une compétition entre IA et élèves", situation: "Le CDI organise un défi : résoudre une énigme documentaire plus vite qu'une IA, en n'utilisant que des sources classiques (livres, bases de données).", altA: "Je participe avec plaisir. C'est un bon moyen de mesurer ce que je sais vraiment faire sans IA.", altB: "Je trouve l'exercice un peu dépassé. Dans la vraie vie, j'aurai toujours accès à l'IA, autant s'entraîner avec." },
  { id: 83, titre: "Des devoirs adaptés à mon rythme, tout le temps", situation: "Une IA adaptative me propose des exercices toujours calibrés exactement à mon niveau du moment, sans jamais me confronter à quelque chose de trop difficile.", altA: "Je trouve ça motivant. Je ne me décourage jamais parce que c'est toujours à ma portée.", altB: "Je préfère parfois affronter des exercices trop difficiles. C'est aussi comme ça qu'on progresse vraiment." },
  { id: 84, titre: "Une IA embarquée dans mes lunettes ou mon casque", situation: "Une nouvelle génération de lunettes connectées peut m'afficher en direct des informations générées par IA pendant que je me promène ou que je visite un musée.", altA: "Ça m'intéresse. Avoir des explications en direct enrichit ce que je vois, sans rien chercher activement.", altB: "Je préfère sans. Je préfère observer et me poser mes propres questions avant de chercher les réponses." },
  { id: 85, titre: "Recommander l'IA à un plus jeune", situation: "Mon petit frère en primaire me demande comment utiliser l'IA que j'utilise pour mes devoirs de collège.", altA: "Je lui montre, en adaptant à son niveau. Autant qu'il apprenne tôt à s'en servir intelligemment.", altB: "Je lui dis d'attendre. À son âge, je pense qu'il vaut mieux d'abord apprendre à faire sans." },
  { id: 86, titre: "Une IA analyse mes matchs", situation: "Mon club de foot propose une appli qui analyse mes matchs filmés avec l'IA pour repérer mes points faibles techniques, sans passer par l'œil de l'entraîneur.", altA: "Je l'utilise avec plaisir. Ça me donne des retours détaillés que l'entraîneur n'a pas le temps de faire pour chacun.", altB: "Je m'en méfie un peu. Je préfère les retours d'un humain qui connaît mon jeu depuis longtemps, même moins précis." },
  { id: 87, titre: "Une IA compose mon accompagnement", situation: "Pour mon morceau de fin d'année en cours de musique, une IA peut composer un accompagnement instrumental complet à partir de ma mélodie.", altA: "Je l'utilise. Le résultat sonne bien plus riche que ce que je saurais composer seul.", altB: "Je compose moi-même mon accompagnement, même s'il sera plus simple. Je veux que le morceau soit entièrement à moi." },
  { id: 88, titre: "Un projet d'arts plastiques généré", situation: "Pour un projet noté en arts plastiques, je peux utiliser une IA générative pour créer les images de base que je retouche ensuite, ou tout dessiner moi-même depuis le début.", altA: "Je pars d'une image générée par IA. Ça me permet d'aller plus loin dans les finitions plutôt que de bloquer sur l'esquisse.", altB: "Je dessine tout moi-même. Même moins abouti, c'est le seul moyen de vraiment progresser en dessin." },
  { id: 89, titre: "Le journal du collège écrit par IA", situation: "Pour le journal du collège, on peut gagner du temps en demandant à une IA de rédiger un premier jet des articles à partir de nos notes d'interview, sans le préciser aux lecteurs.", altA: "On le fait sans le préciser. Le contenu reste basé sur nos vraies interviews, la rédaction n'a pas besoin d'être signalée.", altB: "On précise l'usage de l'IA dans l'ours du journal. Les lecteurs ont le droit de savoir comment les articles sont produits." },
  { id: 90, titre: "Un voyage scolaire planifié par IA", situation: "Pour préparer notre voyage scolaire, les délégués de classe peuvent utiliser une IA pour construire tout l'itinéraire et les activités, ou le préparer eux-mêmes avec le CDI.", altA: "On utilise l'IA. Elle propose un itinéraire complet en quelques minutes, qu'on n'a plus qu'à valider.", altB: "On le prépare nous-mêmes avec le CDI. C'est plus long, mais on apprend à organiser un vrai projet." },
  { id: 91, titre: "Une lettre de motivation pour mon stage", situation: "Pour mon stage de troisième, je peux demander à une IA de rédiger entièrement ma lettre de motivation, ou l'écrire moi-même en m'inspirant juste d'un exemple.", altA: "Je la laisse rédiger l'essentiel. Le résultat est plus soigné que ce que j'écrirais seul.", altB: "Je l'écris moi-même. Une lettre de motivation doit vraiment venir de moi, même si elle est moins bien tournée." },
  { id: 92, titre: "Une IA anti-gaspillage à la cantine", situation: "La cantine teste un outil d'IA qui prédit combien de plats préparer chaque jour à partir des habitudes de réservation, pour réduire le gaspillage alimentaire.", altA: "Je trouve ça positif. Moins de gaspillage, c'est bon pour tout le monde et pour l'environnement.", altB: "Ça m'inquiète un peu. Et si l'IA se trompe un jour et qu'il n'y a plus assez à manger pour tous ?" },
  { id: 93, titre: "Un arbitre IA pour le tournoi interne", situation: "Pour le tournoi sportif inter-classes, le foyer propose d'utiliser une appli d'IA qui arbitre certains matchs à partir de la vidéo, plutôt que des élèves volontaires.", altA: "Je préfère l'IA. Elle ne favorise personne et évite les disputes sur les décisions arbitrales.", altB: "Je préfère des élèves arbitres. Ça reste notre tournoi, entre nous, avec ses imperfections humaines." },
  { id: 94, titre: "Le CDI qui recommande mes lectures", situation: "Le CDI propose un outil qui recommande des livres personnalisés à partir de mes précédents emprunts, plutôt que de demander conseil au professeur documentaliste.", altA: "J'utilise les recommandations de l'outil. Elles correspondent bien à ce que j'aime déjà lire.", altB: "Je préfère demander au professeur documentaliste. Il peut me faire découvrir des choses auxquelles je n'aurais pas pensé." },
  { id: 95, titre: "Le compte-rendu du conseil de discipline", situation: "En tant que délégué, je participe à la rédaction du compte-rendu d'un conseil de discipline. Une IA peut le rédiger à partir de mes notes prises en séance.", altA: "Je la laisse rédiger le compte-rendu. Ça évite les oublis et c'est plus rapide à produire.", altB: "Je le rédige moi-même, phrase par phrase. C'est un document sensible, je veux garder le contrôle total sur ce qu'il dit." },
  { id: 96, titre: "Identifier les espèces en sortie nature", situation: "En sortie nature, je peux utiliser une appli d'IA qui identifie instantanément les plantes et insectes que je photographie, ou essayer d'abord avec le guide botanique papier.", altA: "J'utilise l'appli. C'est immédiat, et je peux identifier beaucoup plus d'espèces en une sortie.", altB: "J'essaie d'abord avec le guide papier. Chercher moi-même m'aide à mieux retenir ce que j'apprends." },
  { id: 97, titre: "Des dialogues générés pour la pièce de théâtre", situation: "Pour la pièce du club théâtre, on peut demander à une IA de générer des dialogues à partir de notre synopsis, ou les écrire nous-mêmes en atelier d'écriture collective.", altA: "On utilise l'IA pour un premier jet, qu'on retravaille ensuite ensemble. Ça débloque plus vite l'écriture.", altB: "On écrit tout nous-mêmes en atelier. C'est plus lent, mais le texte final nous ressemble vraiment." },
  { id: 98, titre: "Un journal intime commenté par une IA", situation: "Une appli de journal intime propose de commenter mes entrées avec une IA bienveillante, qui répond à ce que j'écris comme le ferait un confident.", altA: "Je trouve ça réconfortant d'avoir un retour, même s'il vient d'une IA, plutôt que d'écrire dans le vide.", altB: "Je préfère qu'il reste vraiment intime, sans aucun retour, même bienveillant. Ça change tout de savoir qu'on me répond." },
  { id: 99, titre: "Une IA qui démarche les entreprises pour mon stage", situation: "Pour trouver mon stage de troisième, une IA peut identifier et contacter automatiquement des entreprises proches de chez moi en mon nom, ou je peux le faire moi-même, appel par appel.", altA: "Je la laisse faire. Elle contacte beaucoup plus d'entreprises que je ne pourrais le faire seul.", altB: "Je le fais moi-même. C'est stressant, mais c'est aussi ma première vraie expérience de démarche professionnelle." },
  { id: 100, titre: "Mon auto-évaluation de fin d'année", situation: "Pour le bilan de fin d'année à remplir avec mon professeur principal, une IA peut rédiger une auto-évaluation soignée à partir de mes notes et de quelques mots-clés que je lui donne.", altA: "Je la laisse rédiger l'essentiel. Le résultat est plus clair que ce que j'écrirais moi-même.", altB: "Je l'écris moi-même, même maladroitement. Ce bilan doit refléter comment je vois vraiment mon année." },
];

export const ICON_KEYS = {
  1: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  2: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  3: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  4: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  5: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  6: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  7: { a: ["img_inclusivity.png"], b: ["img_equality.png"] },
  8: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  9: { a: ["img_bonpublic.png", "img_Gaspillage.png"], b: ["img_critique.png", "img_Frugalite.png"] },
  10: { a: ["img_equality.png"], b: ["img_bonpublic.png"] },
  11: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  12: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  13: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  14: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  15: { a: ["img_USERascendant.png", "img_Gaspillage.png"], b: ["img_Integrite.png", "img_Frugalite.png"] },
  16: { a: ["img_USERascendant.png", "img_delestage.png"], b: ["img_Integrite.png", "img_MonteeCptces.png"] },
  17: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  18: { a: ["img_data.png"], b: ["img_datacloud.png"] },
  19: { a: ["img_Gaspillage.png", "img_delestage.png"], b: ["img_Frugalite.png", "img_MonteeCptces.png"] },
  20: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  21: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  22: { a: ["img_critique.png", "img_Gaspillage.png"], b: ["img_delestage.png", "img_Frugalite.png"] },
  23: { a: ["img_delestage.png", "img_Gaspillage.png"], b: ["img_MonteeCptces.png", "img_Frugalite.png"] },
  24: { a: ["img_USERascendant.png"], b: ["img_IAascendant.png"] },
  25: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  26: { a: ["img_delestage.png", "img_IAascendant.png"], b: ["img_MonteeCptces.png", "img_USERascendant.png"] },
  27: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  28: { a: ["img_bonpublic.png", "img_data.png"], b: ["img_critique.png", "img_datacloud.png"] },
  29: { a: ["img_IAascendant.png", "img_data.png"], b: ["img_Integrite.png", "img_datacloud.png"] },
  30: { a: ["img_BoiteNoire.png", "img_IAascendant.png"], b: ["img_Tsprence.png", "img_USERascendant.png"] },
  31: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  32: { a: ["img_Inegalite.png"], b: ["img_equality.png"] },
  33: { a: ["img_USERascendant.png", "img_Errors.png"], b: ["img_equality.png", "img_Integrite.png"] },
  34: { a: ["img_Integrite.png", "img_equality.png"], b: ["img_Integrite.png", "img_inclusivity.png"] },
  35: { a: ["img_Robbery.png"], b: ["img_critique.png"] },
  36: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  37: { a: ["img_bonpublic.png", "img_Inegalite.png"], b: ["img_critique.png", "img_inclusivity.png"] },
  38: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
  39: { a: ["img_USERascendant.png", "img_inclusion.png"], b: ["img_USERascendant.png"] },
  40: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  41: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  42: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  43: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  44: { a: ["img_equality.png"], b: ["img_Inegalite.png"] },
  45: { a: ["img_Tsprence.png"], b: ["img_BoiteNoire.png"] },
  46: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  47: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  48: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  49: { a: ["img_inclusivity.png"], b: ["img_Inegalite.png"] },
  50: { a: [], b: [] },
  51: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  52: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  53: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  54: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  55: { a: ["img_Gaspillage.png"], b: ["img_Frugalite.png"] },
  56: { a: ["img_Tsprence.png"], b: ["img_BoiteNoire.png"] },
  57: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  58: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  59: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  60: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  61: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  62: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  63: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  64: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  65: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  66: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  67: { a: ["img_Frugalite.png"], b: ["img_Gaspillage.png"] },
  68: { a: ["img_data.png"], b: ["img_datacloud.png"] },
  69: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  70: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  71: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  72: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  73: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  74: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  75: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  76: { a: ["img_inclusivity.png"], b: ["img_Inegalite.png"] },
  77: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  78: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  79: { a: ["img_Integrite.png"], b: ["img_Duplicite.png"] },
  80: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  81: { a: ["img_datacloud.png"], b: ["img_data.png"] },
  82: { a: ["img_MonteeCptces.png"], b: ["img_delestage.png"] },
  83: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  84: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  85: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  86: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  87: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  88: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  89: { a: ["img_Duplicite.png"], b: ["img_Integrite.png"] },
  90: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  91: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  92: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  93: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  94: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  95: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  96: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  97: { a: ["img_bonpublic.png"], b: ["img_critique.png"] },
  98: { a: ["img_IAascendant.png"], b: ["img_USERascendant.png"] },
  99: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
  100: { a: ["img_delestage.png"], b: ["img_MonteeCptces.png"] },
};

export const ICON_MAX = {
  "img_delestage.png": 26,
  "img_MonteeCptces.png": 25,
  "img_critique.png": 21,
  "img_bonpublic.png": 20,
  "img_USERascendant.png": 19,
  "img_Gaspillage.png": 16,
  "img_Frugalite.png": 16,
  "img_IAascendant.png": 14,
  "img_Integrite.png": 14,
  "img_datacloud.png": 11,
  "img_data.png": 11,
  "img_Duplicite.png": 8,
  "img_equality.png": 6,
  "img_inclusivity.png": 5,
  "img_Inegalite.png": 5,
  "img_Tsprence.png": 3,
  "img_BoiteNoire.png": 3,
  "img_inclusion.png": 2,
  "img_Errors.png": 1,
  "img_Robbery.png": 1,
};

export const BILAN_CARDS = [
  {
    img1: "img_bonpublic.png",
    title1: "Bon public",
    desc1: "Tu acceptes d'utiliser ces outils, sans trop te pr\u00e9occuper de leur fonctionnement ou de leurs limites. Tant qu'ils fonctionnent, le reste t'importe peu.",
    img2: "img_critique.png",
    title2: "Esprit critique",
    desc2: "Pas question d'utiliser des outils sans comprendre leurs enjeux. Il faut que tu comprennes tous les aspects, toutes les cons\u00e9quences de leur utilisation.",
  },
  {
    img1: "img_delestage.png",
    title1: "D\u00e9lestage cognitif",
    desc1: "Tu abandonnes \u00e0 l'IA des t\u00e2ches qui sont importantes pour le d\u00e9veloppement g\u00e9n\u00e9ral de tes comp\u00e9tences.",
    img2: "img_MonteeCptces.png",
    title2: "Mont\u00e9e en comp\u00e9tences",
    desc2: "Tu gardes la main sur le d\u00e9veloppement de tes comp\u00e9tences, en utilisant l'IA pour des t\u00e2ches pr\u00e9cises, mais pas essentielles.",
  },
  {
    img1: "img_Duplicite.png",
    title1: "Duplicit\u00e9",
    desc1: "Tu utilises l'IA de fa\u00e7on cach\u00e9e, sans la d\u00e9clarer et parfois, en faisant passer son travail pour le tien.",
    img2: "img_Integrite.png",
    title2: "Int\u00e9grit\u00e9",
    desc2: "Tu es transparent sur ton utilisation de l'IA. Tu la d\u00e9clares de fa\u00e7on honn\u00eate, en pr\u00e9cisant o\u00f9 et pourquoi tu l'as utilis\u00e9e.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9, ou que tu n'interviens plus pour contr\u00f4ler son fonctionnement.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches, sans que tu v\u00e9rifies ou que tu critiques ce qu'elle fait.",
  },
  {
    img1: "img_Time.png",
    title1: "Temps",
    desc1: "L'usage de l'IA est motiv\u00e9 par le gain de temps : certaines t\u00e2ches sont faites automatiquement et sans effort.",
    img2: "img_inclusion.png",
    title2: "\u00c9tayage et inclusion",
    desc2: "En s'appuyant sur un profil personnalis\u00e9, l'IA est capable d'adapter ses r\u00e9ponses \u00e0 l'utilisateur. Elle peut aussi compenser certaines de ses difficult\u00e9s.",
  },
  {
    img1: "img_Robbery.png",
    title1: "Pillage",
    desc1: "L'utilisation de l'IA ne respecte pas les droits des auteurs. M\u00eame si elle transforme ces sources, elle les utilise sans citer et sans r\u00e9tribuer les cr\u00e9ateurs.",
    img2: "img_Time.png",
    title2: "Respect des droits",
    desc2: "Tu es conscient que l'IA peut utiliser des sources prot\u00e9g\u00e9es par des droits d'auteur. Pour toi, c'est un aspect important.",
  },
  {
    img1: "img_Frugalite.png",
    title1: "Frugalit\u00e9 / \u00e9conomie",
    desc1: "Tes choix montrent une volont\u00e9 de ne pas gaspiller les ressources naturelles.",
    img2: "img_Gaspillage.png",
    title2: "Gaspillage",
    desc2: "Ta pratique r\u00e9p\u00e9t\u00e9e ou maladroite de l'IA consomme beaucoup de ressources naturelles et impacte l'environnement.",
  },
  {
    img1: "img_BoiteNoire.png",
    title1: "Bo\u00eete noire",
    desc1: "Tu ne sais pas comment fonctionnent les outils d'IA. Ces outils sont comme des \"bo\u00eetes noires\" qui agissent de fa\u00e7on un peu magique.",
    img2: "img_Tsprence.png",
    title2: "Transparence de fonctionnement",
    desc2: "Pour toi, il est essentiel que tu comprennes le fonctionnement, pour que tu utilises ces outils de fa\u00e7on r\u00e9fl\u00e9chie.",
  },
  {
    img1: "img_equality.png",
    title1: "\u00c9galitaire",
    desc1: "Tu es d'accord pour dire que l'IA doit s'adresser \u00e0 tout le monde. Elle doit s'adapter aux minorit\u00e9s, aux personnes en difficult\u00e9.",
    img2: "img_Inegalite.png",
    title2: "In\u00e9galitaire",
    desc2: "On ne pourra pas faire en sorte que l'IA soit utilis\u00e9e par tout le monde de la m\u00eame mani\u00e8re. Tant pis si \u00e7a doit cr\u00e9er ou empirer les in\u00e9galit\u00e9s.",
  },
  {
    img1: "img_datacloud.png",
    title1: "S\u00e9curit\u00e9 des donn\u00e9es",
    desc1: "Les donn\u00e9es d'entra\u00eenement ou d'utilisation de l'IA doivent \u00eatre v\u00e9rifi\u00e9es. On r\u00e9duit ainsi le risque d'erreur ou l'usage de donn\u00e9es non autoris\u00e9es.",
    img2: "img_data.png",
    title2: "Open Data",
    desc2: "Peu importe les donn\u00e9es utilis\u00e9es par l'IA. Plus il y en a, plus les r\u00e9sultats seront pertinents, selon toi.",
  },
  {
    img1: "img_CultureRespect.png",
    title1: "Respect des cultures",
    desc1: "Tu sais que l'IA favorise certaines cultures. Elle poss\u00e8de des biais culturels. Tu aimerais qu'elle prenne en compte davantage de cultures.",
    img2: "img_CultureHegemonie.png",
    title2: "Culture h\u00e9g\u00e9monique",
    desc2: "L'IA se nourrit surtout des cultures de langue anglaise. Il faut accepter que certaines cultures soient majoritaires.",
  },
  {
    img1: "img_IAascendant.png",
    title1: "L'IA prend l'ascendant",
    desc1: "L'IA ma\u00eetrise ton processus d'apprentissage, parce qu'il est enti\u00e8rement automatis\u00e9.",
    img2: "img_USERascendant.png",
    title2: "L'utilisateur garde l'ascendant",
    desc2: "Tu restes en contr\u00f4le : tu ne laisses pas l'IA faire toutes les t\u00e2ches sans que tu v\u00e9rifies ce qu'elle fait.",
  },
];
